export const translationRecord = {
  coPilotLbl: 'Assistify',
  poweredByAILbl: 'Powered by AI',
  resetChatLbl: 'Reset Chat',
  coPilotPlaceHolderLbl: 'E.g. Tell me about calendar ? ',
  welcomeAILbl: 'Welcome to Assistify',
  welcomeAISubtextLbl:
    'Your ultimate AI-powered work assistant. \nSeek assistance by asking questions on how to use any application feature.',
  askHeadingLbl: 'Ask Assistify how to use any application feature ?',
  introPanelAIOne: 'How can I effectively manage my time?',
  introPanelAITwo: 'What are some tips for improving my productivity?',
  introPanelAIThree: 'What resources do you recommend for learning new skills?',
  seePreviewLbl: 'See Preview',
  videoLbl: 'Video',
  provideAdditionalFeedbackLbl: 'Provide Additional Feedback',
  downvoteOptionalLbl: '(Optional) Add specific details here',
  downvoteMaxLengthErrLbl: 'Reached max allowed character limit',
  misunderstoodQuestionLbl: 'Misnderstood Question',
  misleadingInformationLbl: 'Misleading Information',
  offTopicResponseLbl: 'Off-Topic Response',
  incompleteAnswerLbl: 'Incomplete Answer',
  notWhatIWasLookingFor: 'Not What I Was Looking For',
  notUseful: 'Not Useful',
  otherLbl: 'Other',
  responseCopiedLbl: 'Response Copied',
  copyResponseLbl: 'Copy Response',
  thanksFeedbackLbl: 'Thanks for your feedback!',
  relatedTopicsLbl: 'Related Topics',
  submitBtnText: 'Submit',
  goodResponseLbl: 'Good Response',
  badResponseLbl: 'Bad Response',
};
